#!/usr/bin/env python3

# Danfe- One stop solution to all your file transformation needs!
# Copyright (C) 2020-2021  Shrid Pant

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

import os
import argparse
import textwrap
from src.danfe import Danfe
from src.logger import Logger
from src.utils.utils import ErrorHandler, Save

version = '0.1'

def main():
    file_path, verbose, quiet, convert_to, save_location = parse_arguments()
    danfe_logger = Logger(verbose)
    file_object = Danfe(file_path, danfe_logger)
    result = convert_file(file_object, convert_to, danfe_logger)
    if quiet:
        danfe_logger.log(result)
    else:
        danfe_logger.log(result, display=True)
    if save_location:
        danfe_save = Save(result, save_location, convert_to, danfe_logger)
        danfe_save.save()
    danfe_logger.log(status_message = __name__, status_code = 0)
    input(">> Press enter to continue ...")

def convert_file(file_to_convert, convert_to, logger):
    if convert_to == "list":
        converted_file = file_to_convert.to_list()
    elif convert_to == "dict":
        converted_file = file_to_convert.to_dict()
    elif convert_to.upper() == "JSON":
        converted_file = file_to_convert.to_JSON()
    elif convert_to.upper() == "CSV":
        converted_file = file_to_convert.to_CSV()
    else:
        logger.log("Unknown file option", 400, convert_file.__name__, -1)
        converted_file = None
    return converted_file

def parse_arguments():
    PARSER = argparse.ArgumentParser(
        prog = "danfe",
        formatter_class = argparse.RawTextHelpFormatter,
        description = 'danfe allows transformation of data/files to and from json, csv, list and dictionary.',
        epilog = textwrap.dedent('''\
            danfe Copyright (C) 2020-2021  Shrid Pant
            This program comes with ABSOLUTELY NO WARRANTY.
            This is free software, and you are welcome to redistribute it 
            under certain conditions. For details, see <https://www.gnu.org/licenses/>.
            '''))
    PARSER.add_argument('--version', action = 'version', version = str('%(prog)s '+ version))
    PARSER.add_argument("-v", "--verbose", help = "enable verbose mode", action = "store_true")
    PARSER.add_argument("-q", "--quiet", help = "enable quiet mode", action = "store_true")
    PARSER.add_argument("-s", "--save", metavar = "LOCATION", help = "absolute or relative path to save the output")
    PARSER.add_argument("filename", metavar = "FILENAME", help = "absolute or relative path to the argument file")
    PARSER.add_argument("-t", "--target", choices = ["list", "dict", "json", "csv"], required = True, help = "target file format or data structure to convert to")
    ARGV = PARSER.parse_args()
    if ARGV.verbose and ARGV.quiet:
        PARSER.error('--verbose and --quiet must not be provided together')
    if not os.path.isabs(ARGV.filename):
        ARGV.filename = os.getcwd() + "/" + ARGV.filename
    if ARGV.save and not os.path.isabs(ARGV.save):
        if ARGV.save != ".":
            ARGV.save = os.getcwd() +  "/" + ARGV.save
        else:
            ARGV.save = os.getcwd()
    return ARGV.filename, ARGV.verbose, ARGV.quiet, ARGV.target, ARGV.save

if __name__ == '__main__' :
    try:
        main()
    except ErrorHandler as e:
        print(e)